packages = [
    "pandas"
]

[[fetch]]
files = [
    "/python/utils/generate_group_data.py", 
    "/python/utils/generate_yr_data.py", 
    "/python/utils/generate_sex_data.py",
    "/python/utils/generate_select_district_data.py",
    "/python/utils/generate_select_school_type_data.py",
    "/python/utils/generate_select_school_name_data.py"
]